# 文件存储路径
file:
  mac:
    path: ~/Documents/code/open_sources_project/file/
    avatar: ~/Documents/code/open_sources_project/avatar/
  linux:
    path: /cloud/kindergarten/data/static/
    avatar: /cloud/kindergarten/data/static/
  windows:
    path: D:\cloud\file\
    avatar: D:\cloud\avatar\
  avatarMaxSize: 5