# 数据源
spring:
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/platform?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: sdsadmin
    password: 123456
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    hikari:
      maximum-pool-size: 4
      pool-name: hikari-pool
      max-lifetime: 300000 #5分钟

swagger:
  enabled: true