mybatis-plus:
  global-config:
    banner: false
  mapper-locations: classpath*:/mapper/*.xml

logging:
  level:
    jdbc:
      onlysql: debug
      sqltiming: off
      connection: off
      resultset: off
      resultsettable: off
      audit: off

spring:
  application:
    name: platform

  profiles:
    include:
      - captcha
      - jwt
      - login
      - rsa
      - redis
      - file
      - @activeEnvProfile@

  jackson:
    serialization:
      write-dates-as-timestamps: true