server:
  servlet:
    context-path: /platform

mybatis-plus:
  global-config:
    banner: false
  mapper-locations: classpath*:/mapper/*.xml

logging:
  level:
    jdbc:
      onlysql: debug
      sqltiming: off
      connection: off
      resultset: off
      resultsettable: off
      audit: off
  file:
    path: /cloud/kindergarten/data/log/

spring:
  profiles:
    include:
      - captcha
      - jwt
      - login
      - rsa
      - redis
      - file
      - @activeEnvProfile@

  jackson:
    serialization:
      write-dates-as-timestamps: true

  servlet:
    multipart:
      max-file-size: 20MB
