captcha:
  #  验证码类型配置
  code-type: arithmetic
  #  登录图形验证码有效时间(秒)
  expiration: 120
  #  验证码高度
  width: 111
  #  验证码宽度
  heigth: 36
  # 内容长度
  length: 2
  # 字体名称，为空则使用默认字体
  font-name:
  # 字体大小
  font-size: 25
